version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongo:27017/codeforces
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    restart: always
    ports:
      - "4173:4173"
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge